<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ClubOps.ErpMiddleware.Api\ClubOps.ErpMiddleware.Api.csproj" />
    <ProjectReference Include="..\ClubOps.ErpMiddleware.Application\ClubOps.ErpMiddleware.Application.csproj" />
    <ProjectReference Include="..\ClubOps.ErpMiddleware.Infrastructure\ClubOps.ErpMiddleware.Infrastructure.csproj" />
    <ProjectReference Include="..\ClubOps.ErpMiddleware.Domain\ClubOps.ErpMiddleware.Domain.csproj" />
    <ProjectReference Include="..\ClubOps.ErpMiddleware.Shared\ClubOps.ErpMiddleware.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
