<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClubOps.ErpMiddleware.Application\ClubOps.ErpMiddleware.Application.csproj" />
    <ProjectReference Include="..\ClubOps.ErpMiddleware.Infrastructure\ClubOps.ErpMiddleware.Infrastructure.csproj" />
    <ProjectReference Include="..\ClubOps.ErpMiddleware.Shared\ClubOps.ErpMiddleware.Shared.csproj" />
  </ItemGroup>

</Project>
